### ISSUE TITLE
heronstreaming.io out of date wrt compilation instructions

### ISSUE THREAD

**Issue by srkukarni** [apache/incubator-heron#2523]
CPP bindings introduced cereal library which needs cmake-2.2 which is not the default version of cmake that comes with ubuntu. Thus to compile latest heron, we need to update the instructions to upgrade the cmake.

**Comment by Code0x58** [comment]
keeping these up to date feels a bit redundant. `./bazel_configure.py` seems to be a good tools if you want to compile anywhere supported, otherwise there is the vagrant setup, or Dockerfiles - it may be good to refer to those to keep things DRY - as people will have a copy of the codebase anyway if compiling.

**Comment by joshfischer1108** [comment]
Agreed. Thanks @Code0x58 .
