### ISSUE TITLE
can not get install sh

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3465]
wget https://github.com/apache/incubator-heron/releases/download/0.20.2-incubating/heron-install-0.20.2-incubating-ubuntu.sh
--2020-02-21 10:55:21--  https://github.com/apache/incubator-heron/releases/download/0.20.2-incubating/heron-install-0.20.2-incubating-ubuntu.sh
正在解析主机 github.com (github.com)... 52.74.223.119
正在连接 github.com (github.com)|52.74.223.119|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2020-02-21 10:55:22 错误 404：Not Found。

**Comment by joshfischer1108** [comment]
@dttlgotv This is mistake in the documentation that needs to be corrected. Prior to Heron being donated to the ASF all of the releases were made in Github.  Now that Heron is part of the Apache Foundation we need to go through a different release process as well as host the convenience binaries on Apache infrastructure for distribution.  We are close to getting to that point, but still have a little bit of work to do.  If you want to build the install script for a platform you can run the following command 
```
$ bazel build --config=darwn/ubuntu/centos/debian scripts/packages:binpkgs
```
However, instead of having `darwn/ubuntu/centos/debian` as the config parameter value you need to select one OS value.

MacOs would be `--config=darwin`
Debian would be `--config=debian`
Ubuntu would be `--config=ubuntu`
Centos would be `--config=centos`

The output will be a file named `heron-install.sh` if I remember correctly.

**Comment by dttlgotv** [comment]
> @dttlgotv This is mistake in the documentation that needs to be corrected. Prior to Heron being donated to the ASF all of the releases were made in Github. Now that Heron is part of the Apache Foundation we need to go through a different release process as well as host the convenience binaries on Apache infrastructure for distribution. We are close to getting to that point, but still have a little bit of work to do. If you want to build the install script for a platform you can run the following command
> 
> ```
> $ bazel build --config=darwn/ubuntu/centos/debian scripts/packages:binpkgs
> ```
> 
> However, instead of having `darwn/ubuntu/centos/debian` as the config parameter value you need to select one OS value.
> 
> MacOs would be `--config=darwin`
> Debian would be `--config=debian`
> Ubuntu would be `--config=ubuntu`
> Centos would be `--config=centos`
> 
> The output will be a file named `heron-install.sh` if I remember correctly.

I have some comping errors #3463  , so I have to install the newest version using this way.
