### ISSUE TITLE
Upgrade to Log4J 2.x

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3762]
We should upgrade our Log4J dependency to 2.x. There is a migration guide that mentions an adapter that could help our 1.x code work with the newer log4j 2.17.1 dependency.

https://logging.apache.org/log4j/2.x/manual/migration.html

**Comment by surahman** [comment]
I believe it would be a fairly quick fix to employ the bridge adapter in **_Option 1_**.

I had a look at **_Option 2_** in the list and I could not find references to most of the mentioned functions. There are similarly named logging functions for Python but the logging backend for them is different. The two areas in **_Option 2_** that will raise issues:

* `String concatenation like logger.info("hi " + userName)`
* `Calls to org.apache.log4j.Logger.setLevel() or similar methods`

Because of the line length cap at 80 (why? this max line length is a legacy from the punched card era), we have to split line lengths. I mostly used format strings because they are more efficient but there were places in the code where there was the use of concatenation.

We do set levels for logging, but this is mostly through a parameter to the log message function. I could not find a reference to the use of `setLevel` in the Java codebase.

**Comment by thinker0** [comment]
Wouldn't it be better to use slf4j-over-log4j, logback?

**Comment by thinker0** [comment]
Change log4j to slf4j of Logging
https://github.com/apache/incubator-heron/pull/3791

**Comment by nicknezis** [comment]
Resolved by #3791
